version: '3.8'
services:

  devcontainer:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - localstack
      - cognito-local

  localstack:
    # LocalStack container
    image: localstack/localstack:latest
    ports:
      # Map the port so you can access the API from the host machine
      - 4566:4566
    # volumes:
    #   # Here you mount your setup file so it will be executed
    #   # when the container starts
    #   - ./localstack-setup.sh:/etc/localstack/init/ready.d/script.sh
    #   - ./friendly-sites-table-schema.json:/etc/friendly-sites-table-schema.json

  cognito-local:
    image: jagregory/cognito-local:3.23.3
    ports:
      - 9229:9229
